#include <stdio.h>
#include <stdlib.h>

int abs(int x)
{
    if(x>0)
        return x;
    else 
        return -x;
}


int main(int argc, char *argv[]){

    int width = 256;
    int height = 256;
    int threshold = 120;
    int fuzz_diameter=10;
    int delta = 16;
    int seed=0;

    if (argc<2){
        printf("usage: %s output_file [width [height [seed]]]\n",argv[0]);
        return 0;
    }



    if (argc>2)
    {
        width=atoi(argv[2]);
    }

    if (argc>3)
    {
        height=atoi(argv[3]);
    }

    if (argc>4)
    {
        seed=atoi(argv[4]);
    }

    int image[width][height];
    int i_threshold[width][height];

    printf("writing to %s\n",argv[1]);
    FILE * image_file =fopen(argv[1], "w");
    
    srand(seed);
    
    for(int x = 0; x < width; x ++)
    {
        for(int y = 0;y < height; y ++)
        {
            image[x][y] = (int)((255. * rand()) / RAND_MAX);
        }
    }
    

    for(int round=0;round<2;round++)
    {

        for(int x = 0; x < width; x ++){
            for(int y = 0;y < height; y ++){
                if(image[x][y] < 128 - delta)
                    i_threshold[x][y] = 0;
                else 
                    if (image[x][y] > 128 + delta)
                        i_threshold[x][y] = 255;
                    else 
                        i_threshold[x][y] = 128;
            }
        }

        for(int x=0;x<width;x++)
        {
            for(int y=0;y<height;y++)
            {
                int sum=0;
                int nb=0;
                for(int i = -fuzz_diameter; 
                        i <= fuzz_diameter;
                        i ++)
                {
                    for(int j = -fuzz_diameter+abs(i);
                            j <= fuzz_diameter-abs(i); 
                            j ++)
                    {
                        if (0 <= x + i && x + i < width
                                && 0 <= y+j && y + j < height)
                        {
                            int coeff=2*fuzz_diameter + 2 - abs(i) - abs(j);
                            sum = sum + coeff * i_threshold[x+i][y+j];
                            nb = nb + coeff;
                        }
                    }
                }
                image[x][y] = (sum/nb);
            }
        }
    }


    fprintf(image_file, "P1\n");
    fprintf(image_file, "# random map generated by a small AA script, number %d\n",seed);
    fprintf(image_file, "%d %d\n", width, height);



    for(int y=0;y<height;y++)
    {
        for(int x=0;x<width;x++)
        {
            if(image[x][y] < threshold)
            {
                fprintf(image_file,"%d",1);
            }
            else
            {
                fprintf(image_file,"%d",0);
            }
        }
        fprintf(image_file,"\n");
    }

    fclose(image_file);

    return 0;
}


